apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  labels:
    app: {{ .Values.app.name }}
    environment: {{ .Values.app.environment }}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 300
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      volumes:
      - name: crest
        secret:
          secretName: crest-db-dsn
      containers:
      - name: {{ .Values.app.name }}
        image: "{{ .Values.app.image.name }}:{{ .Values.app.image.tag }}"
        ports:
          - containerPort: {{ .Values.app.image.containerPort }}
        env:
          - name: CREST_ENV
            value: "{{ .Values.app.name }}"
          - name: CREST_DB_MAX_OPEN_CONNS
            value: "{{ .Values.app.database.maxOpenConns }}"
          - name: CREST_DB_MAX_IDLE_CONNS
            value: "{{ .Values.app.database.maxIdleConns }}"
          - name: CREST_DB_MAX_IDLE_TIME
            value: "{{ .Values.app.database.maxIdleTime }}"
          - name: CREST_PORT
            value: "{{ .Values.app.image.containerPort }}"
          - name: CREST_DB_DSN
            valueFrom:
              secretKeyRef:
                name: crest-api-secrets
                key: CREST_DB_DSN     