apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  finalizers: null
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: standard