port = 6996
env = "production"

[db]
user = "crest_api"
port = 17777
password = "valkyrie2"
dbname = "crest_countries"
host = "localhost"
sslrootcert = "/home/sxntana/.crest/ca.pem"
sslcert = "/home/sxntana/.crest/postgresql.pem"
sslkey = "/home/sxntana/.crest/postgresql-key.pem"
sslmode = "disable"

[limiter]
rps = 4.3
burst = 8
enabled = false