geoinfo:
  name: geoinfo
  port: 8080
  # image:
  #   name: "ghcr.io/bxffour/geoinfo/api"
  #   tag: "0.9.0-alpha"
  # configFile: "config.yaml"
  # credsFile: "secret.toml"
  image:
    name: sleeper
    tag: 1.2.0
  config:
    env: staging
    db:
      max-open-conns: 25
      max-idle-conns: 25
      max-idle-time: 35m
    limiter:
      rps: 4.3
      burst: 8
      enabled: true
  database:
    credentials:
      username: "geoinfo"
      password: "valkyrie2"
      database: "geoinfo"
      host: "postgresql.default.svc.cluster.local"
      port: 5432
    tls:
      enable: true
      sslkey: "tls.key"
      sslcert: "tls.crt"
      sslrootcert: "ca.pem"
      sslmode: "require"
      
batch:
  name: "pgdata-dump"
  image:
    name: "ghcr.io/bxffour/crest/bootstrap"
    tag: "1.1.3"
  database:
    user: postgres
    password: valkyrie1
    hostname: postgresql.default.svc.cluster.local
    port: 5432
    database: geoinfo
    tlsenabled: true
    sslkey: tls.key
    sslcert: tls.crt
    sslrootcert: ca.pem
    sslmode: "prefer"
  password:
    # password to set when creating the crest_api user
    apiPassword: "valkyrie2"
