apiVersion: v1
kind: Secret
metadata:
  name: batch-job-secrets
data:
  POSTGRES_DB_DSN: {{ .Values.batch.connectionString | b64enc }}
  CREST_ADMIN_PASSWORD: {{ .Values.batch.passwords.adminPassword | b64enc }}
  CREST_API_PASSWORD: {{ .Values.batch.passwords.apiPassword | b64enc }}

---
apiVersion: v1
kind: Secret
metadata:
  name: crest-api-secrets
data:
  CREST_DB_DSN: "{{ .Values.app.database.connectionString | b64enc }}"