apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.geoinfo.name }}
  labels:
    app: {{ .Values.geoinfo.name }}
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30001
    protocol: TCP
  selector:
    app: {{ .Values.geoinfo.name }}
