app:
  name: crest-countries
  environment: development
  image:
    name: "ghcr.io/bxffour/crest/api"
    tag: "0.0.5"
    containerPort: "8080"
  database:
    # database user
    databaseUser: "crest_api"
    # database password
    databasePassword: "valkyrie2"
    # database 
    database: "crest_countries"
    # database host
    databaseHost: "crest-postgresql.default.svc.cluster.local"
    # database port
    databasePort: 5432
    # max open connections for database connections
    maxOpenConns: "25"
    # max idle connections for database connections
    maxIdleConns: "25"
    # max idle time for database connections
    maxIdleTime: "15m"

# values for the pg-dump job.
batch:
  name: "pgdata-dump"
  image:
    name: "ghcr.io/bxffour/crest/bootstrap"
    tag: "1.1.3"
  connectionString: "postgres://postgres:valkyrie1@crest-postgresql.default.svc.cluster.local:5432/crest_countries?sslmode=disable"
  passwords:
    # password to set when creating the crest_api user
    apiPassword: "valkyrie2"

# values for the bitnami/postgresql helm package
postgresql:
  auth:
    postgresPassword: "valkyrie1"
    database: "crest_countries"

  primary:
    persistence:
      existingClaim: "postgres-pvc"

  image:
    tag: 15.2.0-debian-11-r5
