apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.fullname" . | printf "%s-init" }}
data:
  postgres-dsn: {{ include "postgresDsn" . | b64enc }}
  geoinfo-api-password: {{ .Values.geoinfo.database.credentials.password | b64enc }}
  geoinfo-api-user: {{ .Values.geoinfo.database.credentials.user | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.fullname" . | printf "%s-config" }}
data:
  {{ default "secret.toml" .Values.geoinfo.credsFile -}}: |- 
    {{- include "renderSecret" . | b64enc | nindent 4 -}}
{{ if .Values.geoinfo.config }}
  {{ default "config.yaml" .Values.geoinfo.configFile -}}: |-
    {{- .Values.geoinfo.config | toYaml | b64enc | nindent 4 }}
{{ end }}
