{{- if (include "geoinfo.createCerts" .) -}}
{{- $secretName := printf "%s-crt" (include "common.names.fullname" .) -}}
{{- $ca := genCA "pgclient-ca" 365 -}}
{{- $user := .Values.geoinfo.database.credentials.user -}}
{{- $cert := genSignedCert $user (list) (list) 365 $ca -}}
{{- $tls := .Values.geoinfo.database.tls}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.fullname" . | printf "%s-tls" }}
  namespace: {{ include "common.names.namespace" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
type: kubernetes.io/tls
data:
  {{ $tls.sslcert }}: {{ include "common.secrets.lookup" (dict "secret" $secretName "key" "tls.crt" "defaultValue" $cert.Cert "context" $) }}
  {{ $tls.sslkey }}: {{ include "common.secrets.lookup" (dict "secret" $secretName "key" "tls.key" "defaultValue" $cert.Key "context" $) }}
  {{ $tls.sslrootcert }}: {{ include "common.secrets.lookup" (dict "secret" $secretName "key" "ca.crt" "defaultValue" $ca.Cert "context" $)}}
{{- end -}}