name: Crestcountry API pipeline
on:
  push:
    branches:
      - 'main'
      - 'develop'
jobs:
  release:
    if: ${{ github.ref_name == 'main' }}
    runs-on: ubuntu-latest
    steps:
      -
        name: checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref_name }}
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      -
        name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/crest-countries:latest, ${{ secrets.DOCKER_USERNAME }}/crest-countries:v0.0.${{ github.run_number }}

  release-nightly:
    if: ${{ github.ref_name == 'develop' && github.event_name == 'push' }}
    runs-on: ubuntu-latest
    steps:
      -
        name: checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref_name }}
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      -
        name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/crest-countries:nightly, ${{ secrets.DOCKER_USERNAME }}/crest-countries:0.${{ github.run_number }}.nightly
